Collections:
- Name: SlowFast
  README: configs/recognition/slowfast/README.md
  Paper:
    URL: https://arxiv.org/abs/1812.03982
    Title: SlowFast Networks for Video Recognition
Models:
- Config: configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 36441296896
    Parameters: 34479288
    Pretrained: None
    Resolution: short-side 256
    Training Data: Kinetics-400
    Training Resources: 32 GPUs
  Modality: RGB
  Name: slowfast_r50_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 74.75
      Top 5 Accuracy: 91.73
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/20200731_151706.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/20200731_151706.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth
- Config: configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 36441296896
    Parameters: 34479288
    Pretrained: None
    Resolution: short-side 256
    Training Data: Kinetics-400
    Training Resources: 8 GPUs
  Modality: RGB
  Name: slowfast_r50_video_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 73.95
      Top 5 Accuracy: 91.50
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb/20200812_160237.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb/20200812_160237.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb/slowfast_r50_video_4x16x1_256e_kinetics400_rgb_20200826-f85b90c5.pth
- Config: configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 36441296896
    Parameters: 34479288
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 24 GPUs
  Modality: RGB
  Name: slowfast_r50_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 75.64
      Top 5 Accuracy: 92.3
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/20200704_232901.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/20200704_232901.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth
- Config: configs/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 66222034944
    Parameters: 34565560
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 24 GPUs
  Modality: RGB
  Name: slowfast_r50_8x8x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 76.94
      Top 5 Accuracy: 92.8
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/20200716_192653.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/20200716_192653.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth
- Config: configs/recognition/slowfast/slowfast_r101_r50_4x16x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet101 + ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 65042780160
    Parameters: 62384312
    Pretrained: None
    Resolution: short-side 256
    Training Data: Kinetics-400
    Training Resources: 8 GPUs
  Modality: RGB
  Name: slowfast_r101_r50_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 76.69
      Top 5 Accuracy: 93.07
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_4x16x1_256e_kinetics400_rgb/20210118_133528.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_4x16x1_256e_kinetics400_rgb/20210118_133528.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_4x16x1_256e_kinetics400_rgb/slowfast_r101_4x16x1_256e_kinetics400_rgb_20210218-d8b58813.pth
- Config: configs/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet101
    Batch Size: 8
    Epochs: 256
    FLOPs: 127070375936
    Parameters: 62912312
    Pretrained: None
    Resolution: short-side 256
    Training Data: Kinetics-400
    Training Resources: 32 GPUs
  Modality: RGB
  Name: slowfast_r101_8x8x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 77.9
      Top 5 Accuracy: 93.51
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb/20210218_121513.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb/20210218_121513.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb/slowfast_r101_8x8x1_256e_kinetics400_rgb_20210218-0dd54025.pth
- Config: configs/recognition/slowfast/slowfast_r152_r50_4x16x1_256e_kinetics400_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet152 + ResNet50
    Batch Size: 8
    Epochs: 256
    FLOPs: 91515654144
    Parameters: 84843704
    Pretrained: None
    Resolution: short-side 256
    Training Data: Kinetics-400
    Training Resources: 8 GPUs
  Modality: RGB
  Name: slowfast_r152_r50_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 77.13
      Top 5 Accuracy: 93.2
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r152_4x16x1_256e_kinetics400_rgb/20210122_131321.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r152_4x16x1_256e_kinetics400_rgb/20210122_131321.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r152_4x16x1_256e_kinetics400_rgb/slowfast_r152_4x16x1_256e_kinetics400_rgb_20210122-bdeb6b87.pth
- Config: configs/recognition/slowfast/slowfast_r50_16x8x1_22e_sthv1_rgb.py
  In Collection: SlowFast
  Metadata:
    Architecture: ResNet50
    Batch Size: 4
    Epochs: 22
    FLOPs: 132442627584
    Parameters: 34044630
    Pretrained: Kinetics400
    Resolution: height 100
    Training Data: SthV1
    Training Resources: 8 GPUs
  Modality: RGB
  Name: slowfast_r50_16x8x1_22e_sthv1_rgb
  Results:
  - Dataset: SthV1
    Metrics:
      Top 1 Accuracy: 49.67
      Top 5 Accuracy: 79.00
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_16x8x1_22e_sthv1_rgb/slowfast_r50_16x8x1_22e_sthv1_rgb.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_16x8x1_22e_sthv1_rgb/slowfast_r50_16x8x1_22e_sthv1_rgb.log
  Weights: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_16x8x1_22e_sthv1_rgb/slowfast_r50_16x8x1_22e_sthv1_rgb_20211202-aaaf9279.pth
