Collections:
  - Name: CSN
    README: configs/recognition/csn/README.md
    Paper:
      URL: https://arxiv.org/abs/1904.02811
      Title: 'Video Classification with Channel-Separated Convolutional Networks'

Models:
  - Name: ircsn_ig65m_pretrained_r152_32x2x1_58e_8xb12_kinetics400_rgb
    Config: configs/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_8xb12_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Batch Size: 12
      Epochs: 58
      FLOPs: 98096676864
      Parameters: 29703568
      Pretrained: IG65M
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 82.66
       Top 5 Accuracy: 95.82
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_8xb12_kinetics400_rgb/20220729_134436.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_8xb12_kinetics400_rgb/ircsn_ig65m_pretrained_r152_32x2x1_58e_8xb12_kinetics400_rgb_20220811-c7a3cc5b.pth

  - Name: ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_8xb12_kinetics400_rgb
    Config: configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_8xb12_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Batch Size: 12
      Epochs: 58
      FLOPs: 98096676864
      Parameters: 29703568
      Pretrained: IG65M
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 82.58
       Top 5 Accuracy: 95.76
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_8xb12_kinetics400_rgb/20220729_120335.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_8xb12_kinetics400_rgb/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_8xb12_kinetics400_rgb_20220811-7d1dacde.pth

  - Name: ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_8xb12_kinetics400_rgb
    Config: configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_8xb12_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet50
      Batch Size: 12
      Epochs: 58
      FLOPs: 56209211392
      Parameters: 13131152
      Pretrained: IG65M
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 79.17
       Top 5 Accuracy: 94.14
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_8xb12_kinetics400_rgb/20220731_014145.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_8xb12_kinetics400_rgb/ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_8xb12_kinetics400_rgb_20220811-44395bae.pth

  - Name: ipcsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb
    Config: configs/recognition/csn/ipcsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Epochs: 180
      FLOPs: 110337228800
      Parameters: 33016592
      Pretrained: None
      Resolution: short-side 320
      Training Data: Kinetics-400
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 77.69
       Top 5 Accuracy: 92.93
    Converted From:
      Weights: https://www.dropbox.com/s/3fihu6ti60047mu/ipCSN_152_kinetics_from_scratch_f129594342.pkl?dl=0
      Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
    Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_from_scratch_r152_32x2x1_180e_kinetics400_rgb_20210617-d565828d.pth

  - Name: ircsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb
    Config: configs/recognition/csn/ircsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Epochs: 180
      FLOPs: 98096676864
      Parameters: 29703568
      Pretrained: None
      Resolution: short-side 320
      Training Data: Kinetics-400
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 76.25
       Top 5 Accuracy: 92.11
    Converted From:
      Weights: https://www.dropbox.com/s/46gcm7up60ssx5c/irCSN_152_kinetics_from_scratch_f98268019.pkl?dl=0
      Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
    Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ircsn_from_scratch_r152_32x2x1_180e_kinetics400_rgb_20210617-5c933ae1.pth

  - Name: ipcsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
    Config: configs/recognition/csn/ipcsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Epochs: 58
      FLOPs: 98096676864
      Parameters: 29703568
      Pretrained: IG65M
      Resolution: short-side 320
      Training Data: Kinetics-400
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 82.51
       Top 5 Accuracy: 95.52
    Converted From:
      Weights: https://www.dropbox.com/s/zpp3p0vn2i7bibl/ipCSN_152_ft_kinetics_from_ig65m_f133090949.pkl?dl=0
      Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
    Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-c3be9793.pth

  - Name: ipcsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
    Config: configs/recognition/csn/ipcsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Epochs: 58
      FLOPs: 110337228800
      Parameters: 33016592
      Pretrained: Sports1M
      Resolution: short-side 320
      Training Data: Kinetics-400
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 78.77
       Top 5 Accuracy: 93.78
    Converted From:
      Weights: https://www.dropbox.com/s/ir7cr0hda36knux/ipCSN_152_ft_kinetics_from_sports1m_f111279053.pkl?dl=0
      Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
    Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_sports1m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-3367437a.pth

  - Name: ircsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
    Config: configs/recognition/csn/ircsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
    In Collection: CSN
    Metadata:
      Architecture: ResNet152
      Epochs: 58
      FLOPs: 98096676864
      Parameters: 29703568
      Pretrained: Sports1M
      Resolution: short-side 320
      Training Data: Kinetics-400
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
       Top 1 Accuracy: 78.82
       Top 5 Accuracy: 93.34
    Converted From:
      Weights: https://www.dropbox.com/s/zuoj1aqouh6bo6k/irCSN_152_ft_kinetics_from_sports1m_f101599884.pkl?dl=0
      Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
    Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ircsn_sports1m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-b9b10241.pth
