Collections:
- Name: CSN
  README: configs/recognition/csn/README.md
  Paper:
    URL: https://arxiv.org/abs/1904.02811
    Title: Video Classification with Channel-Separated Convolutional Networks
Models:
- Config: configs/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Batch Size: 3
    Epochs: 58
    FLOPs: 98096676864
    Parameters: 29703568
    Pretrained: IG65M
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 32 GPUs
  Modality: RGB
  Name: ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 80.14
      Top 5 Accuracy: 94.93
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb/20200728_031952.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb/20200728_031952.log
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb/ircsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20200803-fc66ce8d.pth
- Config: configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Batch Size: 3
    Epochs: 58
    FLOPs: 98096676864
    Parameters: 29703568
    Pretrained: IG65M
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 32 GPUs
  Modality: RGB
  Name: ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 82.76
      Top 5 Accuracy: 95.68
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb/20200809_053132.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb/20200809_053132.log
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb_20200812-9037a758.pth
- Config: configs/recognition/csn/ipcsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Epochs: 180
    FLOPs: 110337228800
    Parameters: 33016592
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ipcsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/3fihu6ti60047mu/ipCSN_152_kinetics_from_scratch_f129594342.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 77.8
      Top 5 Accuracy: 92.8
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_from_scratch_r152_32x2x1_180e_kinetics400_rgb_20210617-d565828d.pth
- Config: configs/recognition/csn/ipcsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Epochs: 58
    FLOPs: 110337228800
    Parameters: 33016592
    Pretrained: IG65M
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ipcsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/zpp3p0vn2i7bibl/ipCSN_152_ft_kinetics_from_ig65m_f133090949.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 82.5
      Top 5 Accuracy: 95.3
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_ig65m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-c3be9793.pth
- Config: configs/recognition/csn/ipcsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Epochs: 58
    FLOPs: 110337228800
    Parameters: 33016592
    Pretrained: Sports1M
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ipcsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/ir7cr0hda36knux/ipCSN_152_ft_kinetics_from_sports1m_f111279053.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 78.8
      Top 5 Accuracy: 93.5
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ipcsn_sports1m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-3367437a.pth
- Config: configs/recognition/csn/ircsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Epochs: 180
    FLOPs: 98096676864
    Parameters: 29703568
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ircsn_bnfrozen_r152_32x2x1_180e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/46gcm7up60ssx5c/irCSN_152_kinetics_from_scratch_f98268019.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 76.5
      Top 5 Accuracy: 92.1
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ircsn_from_scratch_r152_32x2x1_180e_kinetics400_rgb_20210617-5c933ae1.pth
- Config: configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet50
    Epochs: 58
    FLOPs: 56209211392
    Parameters: 13131152
    Pretrained: IG65M
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ircsn_ig65m_pretrained_bnfrozen_r50_32x2x1_58e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/gmd8r87l3wmkn3h/irCSN_152_ft_kinetics_from_ig65m_f126851907.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 79.0
      Top 5 Accuracy: 94.2
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ircsn_ig65m_pretrained_r50_32x2x1_58e_kinetics400_rgb_20210617-86d33018.pth
- Config: configs/recognition/csn/ircsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet152
    Epochs: 58
    FLOPs: 98096676864
    Parameters: 29703568
    Pretrained: Sports1M
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ircsn_sports1m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb
  Converted From:
    Weights: https://www.dropbox.com/s/zuoj1aqouh6bo6k/irCSN_152_ft_kinetics_from_sports1m_f101599884.pkl?dl=0
    Code: https://github.com/facebookresearch/VMZ/tree/b61b08194bc3273bef4c45fdfdd36c56c8579ff3
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 78.2
      Top 5 Accuracy: 93.0
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/vmz/vmz_ircsn_sports1m_pretrained_r152_32x2x1_58e_kinetics400_rgb_20210617-b9b10241.pth
- Config: configs/recognition/csn/ircsn_bnfrozen_r50_32x2x1_180e_kinetics400_rgb.py
  In Collection: CSN
  Metadata:
    Architecture: ResNet50
    Epochs: 58
    FLOPs: 56209211392
    Parameters: 13131152
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: ircsn_bnfrozen_r50_32x2x1_180e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 73.6
      top5 accuracy: 91.3
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/csn/ircsn_bnfrozen_r50_32x2x1_180e_kinetics400_rgb/ircsn_bnfrozen_r50_32x2x1_180e_kinetics400_rgb_20210618-4e29e2e8.pth
