blank_issues_enabled: false

contact_links:
  - name: ğŸ“š MMAction2 Documentation (å®˜æ–¹æ–‡æ¡£)
    url: https://mmaction2.readthedocs.io/en/latest
    about: Check if your question is answered in docs
  - name: ğŸ’¬ Forum (å¯»æ±‚å¸®åŠ©)
    url: https://github.com/open-mmlab/mmaction2/discussions
    about: Ask general usage questions and discuss with other MMAction2 community members
  - name: ğŸŒ Explore OpenMMLab (å®˜ç½‘)
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
