Collections:
- Name: I3D
  README: configs/recognition/i3d/README.md
  Paper:
    URL: https://arxiv.org/abs/1705.07750
    Title: 'Quo Vadis, Action Recognition? A New Model and the Kinetics Dataset'

Models:
  - Name: i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      FLOPs: 54334488576
      Parameters: 35397840
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: Kinetics-400
        Task: Action Recognition
        Metrics:
              Top 1 Accuracy: 74.76
              Top 5 Accuracy: 91.84
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-nl-dot-product_8xb8-32x2x1-100e_kinetics400-rgb_20220812-8e1f2148.pth

  - Name: i3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      FLOPs: 54334488576
      Parameters: 35397840
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 74.69
        Top 5 Accuracy: 91.69
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb/ii3d_r50-nl-embedded-gaussian_8xb8-32x2x1-100e_kinetics400-rgb_20220812-afd8f562.pth

  - Name: i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      FLOPs: 48962109440
      Parameters: 31723728
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.90
        Top 5 Accuracy: 91.15
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-nl-gaussian_8xb8-32x2x1-100e_kinetics400-rgb_20220812-0c5cbf5a.pth

  - Name: i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      FLOPs: 43564040192
      Parameters: 28043472
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.22
        Top 5 Accuracy: 91.11
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50_8xb8-32x2x1-100e_kinetics400-rgb_20220812-e213c223.pth

  - Name: i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      FLOPs: 43564040192
      Parameters: 28043472
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.77
        Top 5 Accuracy: 91.35
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb/i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb/i3d_r50_8xb8-dense-32x2x1-100e_kinetics400-rgb_20220812-9f46003f.pth

  - Name: i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb
    Config: configs/recognition/i3d/i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb.py
    In Collection: I3D
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 100
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 76.08
        Top 5 Accuracy: 92.34
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/i3d/i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb/i3d_r50-heavy_8xb8-32x2x1-100e_kinetics400-rgb_20220812-ed501b31.pth
