Collections:
- Name: BSN
  README: configs/localization/bsn/README.md
Models:
- Config:
  - configs/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature.py
  - configs/localization/bsn/bsn_pgm_400x100_activitynet_feature.py
  - configs/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature.py
  In Collection: BSN
  Metadata:
    Pretrained: None
    Training Data: ActivityNet v1.3
    Training Resources: 1 GPUs
    feature: cuhk_mean_100
  Name: bsn_400x100_1x16_20e_activitynet_feature (cuhk_mean_100)
  Results:
  - Dataset: ActivityNet v1.3
    Metrics:
      AR@100: 74.66
      AUC: 66.45
    Task: Temporal Action Localization
  Training Json Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature/bsn_tem_400x100_1x16_20e_activitynet_feature.log.json
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature/bsn_pem_400x100_1x16_20e_activitynet_feature.log.json
  Training Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature/bsn_tem_400x100_1x16_20e_activitynet_feature.log
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature/bsn_pem_400x100_1x16_20e_activitynet_feature.log
  Weights:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature/bsn_tem_400x100_1x16_20e_activitynet_feature_20200619-cd6accc3.pth
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature/bsn_pem_400x100_1x16_20e_activitynet_feature_20210203-1c27763d.pth
- Config:
  - configs/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature.py
  - configs/localization/bsn/bsn_pgm_400x100_activitynet_feature.py
  - configs/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature.py
  In Collection: BSN
  Metadata:
    Pretrained: None
    Training Data: ActivityNet v1.3
    Training Resources: 1 GPUs
    feature: mmaction_video
  Name: bsn_400x100_1x16_20e_activitynet_feature (mmaction_video)
  Results:
  - Dataset: ActivityNet v1.3
    Metrics:
      AR@100: 74.93
      AUC: 66.74
    Task: Temporal Action Localization
  Training Json Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_video/bsn_tem_400x100_1x16_20e_mmaction_video_20200809.json
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_video/bsn_pem_400x100_1x16_20e_mmaction_video_20200809.json
  Training Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_video/bsn_tem_400x100_1x16_20e_mmaction_video_20200809.log
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_video/bsn_pem_400x100_1x16_20e_mmaction_video_20200809.log
  Weights:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_video/bsn_tem_400x100_1x16_20e_mmaction_video_20200809-ad6ec626.pth
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_video/bsn_pem_400x100_1x16_20e_mmaction_video_20200809-aa861b26.pth
- Config:
  - configs/localization/bsn/bsn_pem_400x100_1x16_20e_activitynet_feature.py
  - configs/localization/bsn/bsn_pgm_400x100_activitynet_feature.py
  - configs/localization/bsn/bsn_tem_400x100_1x16_20e_activitynet_feature.py
  In Collection: BSN
  Metadata:
    Pretrained: None
    Training Data: ActivityNet v1.3
    Training Resources: 1 GPUs
    feature: mmaction_clip
  Name: bsn_400x100_1x16_20e_activitynet_feature (mmaction_clip)
  Results:
  - Dataset: ActivityNet v1.3
    Metrics:
      AR@100: 75.19
      AUC: 66.81
    Task: Temporal Action Localization
  Training Json Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_clip/bsn_tem_400x100_1x16_20e_mmaction_clip_20200809.json
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_clip/bsn_pem_400x100_1x16_20e_mmaction_clip_20200809.json
  Training Log:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_clip/bsn_tem_400x100_1x16_20e_mmaction_clip_20200809.log
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_clip/bsn_pem_400x100_1x16_20e_mmaction_clip_20200809.log
  Weights:
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_tem_400x100_1x16_20e_mmaction_clip/bsn_tem_400x100_1x16_20e_mmaction_clip_20200809-0a563554.pth
  - https://download.openmmlab.com/mmaction/localization/bsn/bsn_pem_400x100_1x16_20e_mmaction_clip/bsn_pem_400x100_1x16_20e_mmaction_clip_20200809-e32f61e6.pth
