Collections:
- Name: OmniSource
  README: configs/recognition/omnisource/README.md
Models:
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 77.4
      top5 acc: 93.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/baseline/tsn_r50_1x1x8_100e_minikinetics_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/baseline/tsn_r50_1x1x8_100e_minikinetics_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/baseline/tsn_r50_1x1x8_100e_minikinetics_rgb_20201030-b4eaf92b.pth
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_googleimage_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_googleimage_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 78.0
      top5 acc: 93.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/googleimage/tsn_r50_1x1x8_100e_minikinetics_googleimage_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/googleimage/tsn_r50_1x1x8_100e_minikinetics_googleimage_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/googleimage/tsn_r50_1x1x8_100e_minikinetics_googleimage_rgb_20201030-23966b4b.pth
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_webimage_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_webimage_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 78.6
      top5 acc: 93.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/webimage/tsn_r50_1x1x8_100e_minikinetics_webimage_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/webimage/tsn_r50_1x1x8_100e_minikinetics_webimage_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/webimage/tsn_r50_1x1x8_100e_minikinetics_webimage_rgb_20201030-66f5e046.pth
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_insvideo_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_insvideo_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 80.6
      top5 acc: 95.0
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/insvideo/tsn_r50_1x1x8_100e_minikinetics_insvideo_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/insvideo/tsn_r50_1x1x8_100e_minikinetics_insvideo_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/insvideo/tsn_r50_1x1x8_100e_minikinetics_insvideo_rgb_20201030-011f984d.pth
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_kineticsraw_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_kineticsraw_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 78.6
      top5 acc: 93.2
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/kineticsraw/tsn_r50_1x1x8_100e_minikinetics_kineticsraw_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/kineticsraw/tsn_r50_1x1x8_100e_minikinetics_kineticsraw_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/kineticsraw/tsn_r50_1x1x8_100e_minikinetics_kineticsraw_rgb_20201030-59f5d064.pth
- Config: configs/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics/tsn_r50_1x1x8_100e_minikinetics_omnisource_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 100
    Input: 3seg
    Modality: RGB
    Parameters: 23917832
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: tsn_r50_1x1x8_100e_minikinetics_omnisource_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 81.3
      top5 acc: 94.8
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/omnisource/tsn_r50_1x1x8_100e_minikinetics_omnisource_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/omnisource/tsn_r50_1x1x8_100e_minikinetics_omnisource_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/tsn_r50_1x1x8_100e_minikinetics_rgb/omnisource/tsn_r50_1x1x8_100e_minikinetics_omnisource_rgb_20201030-0f56ef51.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 78.6
      top5 acc: 93.9
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/baseline/slowonly_r50_8x8x1_256e_minikinetics_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/baseline/slowonly_r50_8x8x1_256e_minikinetics_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/baseline/slowonly_r50_8x8x1_256e_minikinetics_rgb_20201030-168eb098.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 80.8
      top5 acc: 95.0
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/googleimage/slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/googleimage/slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/googleimage/slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb_20201030-7da6dfc3.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_webimage_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_webimage_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 81.3
      top5 acc: 95.2
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/webimage/slowonly_r50_8x8x1_256e_minikinetics_webimage_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/webimage/slowonly_r50_8x8x1_256e_minikinetics_webimage_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/webimage/slowonly_r50_8x8x1_256e_minikinetics_webimage_rgb_20201030-c36616e9.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_insvideo_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_insvideo_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 82.4
      top5 acc: 95.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/insvideo/slowonly_r50_8x8x1_256e_minikinetics_insvideo_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/insvideo/slowonly_r50_8x8x1_256e_minikinetics_insvideo_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/insvideo/slowonly_r50_8x8x1_256e_minikinetics_insvideo_rgb_20201030-e2890e8d.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_kineticsraw_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_kineticsraw_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 80.3
      top5 acc: 94.5
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/kineticsraw/slowonly_r50_8x8x1_256e_minikinetics_kineticsraw_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/kineticsraw/slowonly_r50_8x8x1_256e_minikinetics_kineticsraw_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/kineticsraw/slowonly_r50_8x8x1_256e_minikinetics_kineticsraw_rgb_20201030-62974bac.pth
- Config: configs/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics/slowonly_r50_8x8x1_256e_minikinetics_googleimage_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 12
    Epochs: 256
    Input: 8x8
    Modality: RGB
    Parameters: 32044296
    Pretrained: None
    Resolution: short-side 320
    Training Data: MiniKinetics
  Modality: RGB
  Name: slowonly_r50_8x8x1_256e_minikinetics_omnisource_rgb
  Results:
  - Dataset: MiniKinetics
    Metrics:
      top1 acc: 82.9
      top5 acc: 95.8
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/omnisource/slowonly_r50_8x8x1_256e_minikinetics_omnisource_rgb_20201030.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/omnisource/slowonly_r50_8x8x1_256e_minikinetics_omnisource_rgb_20201030.log
  Weights: https://download.openmmlab.com/mmaction/recognition/omnisource/slowonly_r50_8x8x1_256e_minikinetics_rgb/omnisource/slowonly_r50_8x8x1_256e_minikinetics_omnisource_rgb_20201030-284cfd3b.pth
- Config: configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 32
    Epochs: 100
    Parameters: 24327632
    Pretrained: ImageNet
    Resolution: 340x256
    Training Data: Kinetics-400
  Modality: RGB
  Name: tsn_omnisource_r50_1x1x3_100e_kinetics_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 73.6
      top5 acc: 91.0
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/tsn/omni/tsn_imagenet_pretrained_r50_omni_1x1x3_kinetics400_rgb_20200926-54192355.pth
- Config: configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 32
    Epochs: 100
    Parameters: 24327632
    Pretrained: IG-1B
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: tsn_IG1B_pretrained_omnisource_r50_1x1x3_100e_kinetics_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 75.7
      top5 acc: 91.9
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/tsn/omni/tsn_1G1B_pretrained_r50_omni_1x1x3_kinetics400_rgb_20200926-2863fed0.pth
- Config: configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet50
    Batch Size: 8
    Epochs: 256
    Parameters: 32454096
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: slowonly_r50_omnisource_4x16x1_256e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 76.8
      top5 acc: 92.5
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/slowonly/omni/slowonly_r50_omni_4x16x1_kinetics400_rgb_20200926-51b1f7ea.pth
- Config: configs/recognition/slowonly/slowonly_r101_8x8x1_196e_kinetics400_rgb.py
  In Collection: OmniSource
  Metadata:
    Architecture: ResNet101
    Batch Size: 8
    Epochs: 196
    Parameters: 60359120
    Pretrained: None
    Resolution: short-side 320
    Training Data: Kinetics-400
  Modality: RGB
  Name: slowonly_r101_omnisource_8x8x1_196e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 80.4
      top5 acc: 94.4
    Task: Action Recognition
  Weights: https://download.openmmlab.com/mmaction/recognition/slowonly/omni/slowonly_r101_omni_8x8x1_kinetics400_rgb_20200926-b5dbb701.pth
